/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ZIRODESIGN (https://sketchfab.com/zirodesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/technical-difficulties-a1ece2af96c8488e960aab1bb264c37b
Title: “Technical difficulties”
*/

import React, { useRef ,useEffect} from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import Techincal   from "../assets/3d/Techincal.glb";
import { a } from "@react-spring/three";

const Techincal(props) =>{
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/technical_difficulties.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <a.group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="OldTV_03_Low02_OldTV_0_5"
                position={[4.109, 0, -4.122]}
                rotation={[Math.PI / 2, 0, 0.597]}
                scale={0.024}
              >
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.OldTV}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0001_14"
                position={[4.109, 0, -4.122]}
                rotation={[Math.PI / 2, 0, 0.597]}
                scale={0.024}
              >
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0004_15"
                position={[4.152, 0, -4.093]}
                rotation={[Math.PI / 2, 0, 0.597]}
                scale={0.024}
              >
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0002_21"
                position={[6.213, 0, 0.964]}
                rotation={[Math.PI / 2, 0, -0.534]}
                scale={0.024}
              >
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials.OldTV}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0003_30"
                position={[6.213, 0, 0.964]}
                rotation={[Math.PI / 2, 0, -0.534]}
                scale={0.024}
              >
                <mesh
                  name="Object_12"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0004_36"
                position={[1.717, -0.027, 4.62]}
                rotation={[Math.PI / 2, 0, -0.308]}
                scale={0.024}
              >
                <mesh
                  name="Object_14"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials.OldTV}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0005_45"
                position={[1.717, -0.027, 4.62]}
                rotation={[Math.PI / 2, 0, -0.308]}
                scale={0.024}
              >
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0012_46"
                position={[1.767, -0.177, 4.604]}
                rotation={[Math.PI / 2, 0, -0.308]}
                scale={0.024}
              >
                <mesh
                  name="Object_18"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0006_52"
                position={[1.375, 0.026, -9.4]}
                rotation={[Math.PI / 2, 0, 0.401]}
                scale={0.024}
              >
                <mesh
                  name="Object_20"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials.OldTV}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0007_57"
                position={[1.375, 0.026, -9.4]}
                rotation={[Math.PI / 2, 0, 0.401]}
                scale={0.024}
              >
                <mesh
                  name="Object_22"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0016_58"
                position={[1.424, 0.014, -9.38]}
                rotation={[Math.PI / 2, 0, 0.401]}
                scale={0.024}
              >
                <mesh
                  name="Object_24"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0008_59"
                position={[0.974, 3.721, -5.737]}
                rotation={[Math.PI / 2, 0, 0.172]}
                scale={0.024}
              >
                <mesh
                  name="Object_26"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={materials.OldTV}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0009_60"
                position={[0.974, 3.721, -5.737]}
                rotation={[Math.PI / 2, 0, 0.172]}
                scale={0.024}
              >
                <mesh
                  name="Object_28"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0018_61"
                position={[1.025, 3.721, -5.728]}
                rotation={[Math.PI / 2, 0, 0.172]}
                scale={0.024}
              >
                <mesh
                  name="Object_30"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0010_62"
                position={[4.963, 3.721, -1.096]}
                rotation={[Math.PI / 2, 0, -0.207]}
                scale={0.024}
              >
                <mesh
                  name="Object_32"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_32.geometry}
                  material={materials["OldTV.001"]}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0011_63"
                position={[4.963, 3.721, -1.096]}
                rotation={[Math.PI / 2, 0, -0.207]}
                scale={0.024}
              >
                <mesh
                  name="Object_34"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0012_64"
                position={[0.978, 3.721, 2.723]}
                rotation={[Math.PI / 2, 0, -0.644]}
                scale={0.024}
              >
                <mesh
                  name="Object_36"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_36.geometry}
                  material={materials.OldTV}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0013_65"
                position={[0.978, 3.721, 2.723]}
                rotation={[Math.PI / 2, 0, -0.644]}
                scale={0.024}
              >
                <mesh
                  name="Object_38"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_38.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0002_66"
                position={[1.02, 3.721, 2.692]}
                rotation={[Math.PI / 2, 0, -0.644]}
                scale={0.024}
              >
                <mesh
                  name="Object_40"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_40.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0014_67"
                position={[-2.25, 0, -4.342]}
                rotation={[Math.PI / 2, 0, 1.403]}
                scale={0.024}
              >
                <mesh
                  name="Object_42"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_42.geometry}
                  material={materials.OldTV}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0015_70"
                position={[-2.25, 0, -4.342]}
                rotation={[Math.PI / 2, 0, 1.403]}
                scale={0.024}
              >
                <mesh
                  name="Object_44"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_44.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0003_71"
                position={[-1.186, 0, -5.208]}
                rotation={[Math.PI / 2, 0, -2.921]}
                scale={0.024}
              >
                <mesh
                  name="Object_46"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_46.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0017_74"
                position={[-1.692, 0, 1.172]}
                rotation={[Math.PI / 2, 0, 0.882]}
                scale={0.024}
              >
                <mesh
                  name="Object_48"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_48.geometry}
                  material={materials["Material.001"]}
                />
                <mesh
                  name="Object_49"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_49.geometry}
                  material={materials.OldTV}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0018_75"
                position={[2.342, 7.359, -2.843]}
                rotation={[Math.PI / 2, 0, -0.065]}
                scale={[0.023, 0.023, 0.022]}
              >
                <mesh
                  name="Object_51"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_51.geometry}
                  material={materials.OldTV}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0019_76"
                position={[2.342, 7.359, -2.843]}
                rotation={[Math.PI / 2, 0, -0.065]}
                scale={[0.023, 0.023, 0.022]}
              >
                <mesh
                  name="Object_53"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_53.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0020_77"
                position={[-1.023, 7.359, 0.61]}
                rotation={[Math.PI / 2, 0, 0.442]}
                scale={[0.021, 0.022, 0.02]}
              >
                <mesh
                  name="Object_55"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_55.geometry}
                  material={materials.OldTV}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0021_78"
                position={[-1.023, 7.359, 0.61]}
                rotation={[Math.PI / 2, 0, 0.442]}
                scale={[0.021, 0.022, 0.02]}
              >
                <mesh
                  name="Object_57"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_57.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0010_79"
                position={[-0.981, 7.359, 0.63]}
                rotation={[Math.PI / 2, 0, 0.442]}
                scale={[0.021, 0.022, 0.02]}
              >
                <mesh
                  name="Object_59"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_59.geometry}
                  material={materials["SCREEN.001"]}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0022_80"
                position={[-1.091, 7.359, -6.445]}
                rotation={[Math.PI / 2, 0, 0.442]}
                scale={[0.02, 0.017, 0.018]}
              >
                <mesh
                  name="Object_61"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_61.geometry}
                  material={materials.OldTV}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0023_81"
                position={[-1.091, 7.359, -6.445]}
                rotation={[Math.PI / 2, 0, 0.442]}
                scale={[0.02, 0.017, 0.018]}
              >
                <mesh
                  name="Object_63"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_63.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0024_82"
                position={[0.438, 10.612, -1.991]}
                rotation={[Math.PI / 2, 0, 0.301]}
                scale={[0.02, 0.019, 0.018]}
              >
                <mesh
                  name="Object_65"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_65.geometry}
                  material={materials.OldTV}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0025_83"
                position={[0.438, 10.612, -1.991]}
                rotation={[Math.PI / 2, 0, 0.301]}
                scale={[0.02, 0.019, 0.018]}
              >
                <mesh
                  name="Object_67"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_67.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0009_84"
                position={[4.847, 3.639, -1.192]}
                rotation={[Math.PI / 2, 0, -0.199]}
                scale={0.024}
              >
                <mesh
                  name="Object_69"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_69.geometry}
                  material={materials["SCREEN.001"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0008_85"
                position={[0.093, 0.016, 4.025]}
                rotation={[Math.PI / 2, 0, -0.088]}
                scale={0.024}
              >
                <mesh
                  name="Object_71"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_71.geometry}
                  material={materials["SCREEN.001"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0022_86"
                position={[-2.271, -0.051, -6.173]}
                rotation={[Math.PI / 2, 0, 1.611]}
                scale={0.024}
              >
                <mesh
                  name="Object_73"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_73.geometry}
                  material={materials["SCREEN.001"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0021_87"
                position={[2.393, 7.359, -2.846]}
                rotation={[Math.PI / 2, 0, -0.065]}
                scale={[0.023, 0.023, 0.022]}
              >
                <mesh
                  name="Object_75"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_75.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0029_88"
                position={[0.974, 3.721, -5.737]}
                rotation={[Math.PI / 2, 0, 0.18]}
                scale={0}
              >
                <mesh
                  name="Object_77"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_77.geometry}
                  material={materials["SCREEN.003"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0030_89"
                position={[0.978, 3.721, 2.723]}
                rotation={[Math.PI / 2, 0, -0.636]}
                scale={0}
              >
                <mesh
                  name="Object_79"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_79.geometry}
                  material={materials["SCREEN.003"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0031_90"
                position={[1.666, -0.071, 4.642]}
                rotation={[Math.PI / 2, 0, -0.309]}
                scale={0}
              >
                <mesh
                  name="Object_81"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_81.geometry}
                  material={materials["SCREEN.003"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0037_91"
                position={[2.286, 7.258, -2.849]}
                rotation={[Math.PI / 2, 0, -0.062]}
                scale={0.023}
              >
                <mesh
                  name="Object_83"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_83.geometry}
                  material={materials.SCREEN}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0014_92"
                position={[2.29, 7.258, -2.851]}
                rotation={[Math.PI / 2, 0, -0.062]}
                scale={[0.023, 0.023, 0.022]}
              >
                <mesh
                  name="Object_85"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_85.geometry}
                  material={materials["SCREEN.002"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0032_93"
                position={[0.478, 10.612, -1.978]}
                rotation={[Math.PI / 2, 0, 0.301]}
                scale={[0.02, 0.019, 0.018]}
              >
                <mesh
                  name="Object_87"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_87.geometry}
                  material={materials["SCREEN.001"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0042_94"
                position={[-1.052, 7.359, -6.43]}
                rotation={[Math.PI / 2, 0, 0.442]}
                scale={[0.02, 0.017, 0.018]}
              >
                <mesh
                  name="Object_89"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_89.geometry}
                  material={materials["SCREEN.001"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0045_95"
                position={[1.333, 0.014, -9.418]}
                rotation={[Math.PI / 2, 0, 0.401]}
                scale={0.024}
              >
                <mesh
                  name="Object_91"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_91.geometry}
                  material={materials["SCREEN.001"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0046_96"
                position={[6.27, 0.021, 0.961]}
                rotation={[Math.PI / 2, 0, -0.536]}
                scale={0.024}
              >
                <mesh
                  name="Object_93"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_93.geometry}
                  material={materials["SCREEN.001"]}
                />
              </group>
              <group
                name="OldTV_03_Low02_OldTV_0016_97"
                position={[-1.344, 6.335, -1.436]}
                rotation={[0.466, 0.483, 2.139]}
                scale={0.019}
              >
                <mesh
                  name="Object_95"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_95.geometry}
                  material={materials["Material.001"]}
                />
                <mesh
                  name="Object_96"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_96.geometry}
                  material={materials.OldTV}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0005_98"
                position={[-1.124, 4.552, -0.415]}
                rotation={[0.446, 0.487, 2.135]}
                scale={0.018}
              >
                <mesh
                  name="Object_98"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_98.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0047_99"
                position={[-2.038, 2.009, -3.155]}
                rotation={[1.542, 0.001, 1.416]}
                scale={[0.024, 0.026, 0.024]}
              >
                <mesh
                  name="Object_100"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_100.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0048_100"
                position={[-4.548, 0.378, -5.406]}
                rotation={[Math.PI / 2, 0, -1.471]}
                scale={[-0.024, 0.024, 0.024]}
              >
                <mesh
                  name="Object_102"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_102.geometry}
                  material={materials["SCREEN.001"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0049_101"
                position={[-0.971, 2.133, 2.186]}
                rotation={[1.551, 0.021, -2.252]}
                scale={[-0.024, 0.026, 0.024]}
              >
                <mesh
                  name="Object_104"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_104.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0001_102"
                position={[4.056, 0.006, -4.173]}
                rotation={[Math.PI / 2, 0, 0.588]}
                scale={0.024}
              >
                <mesh
                  name="Object_106"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_106.geometry}
                  material={materials.SCREEN}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0006_103"
                position={[4.061, 0.006, -4.172]}
                rotation={[Math.PI / 2, 0, 0.588]}
                scale={0.024}
              >
                <mesh
                  name="Object_108"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_108.geometry}
                  material={materials["SCREEN.002"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0011_104"
                position={[0.785, 3.604, 2.897]}
                rotation={[Math.PI / 2, 0, -0.659]}
                scale={[0.027, 0.027, 0.026]}
              >
                <mesh
                  name="Object_110"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_110.geometry}
                  material={materials.SCREEN}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0017_105"
                position={[0.787, 3.604, 2.892]}
                rotation={[Math.PI / 2, 0, -0.659]}
                scale={0.026}
              >
                <mesh
                  name="Object_112"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_112.geometry}
                  material={materials["SCREEN.002"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0024_106"
                position={[1.392, -0.232, 4.676]}
                rotation={[Math.PI / 2, 0, -0.309]}
                scale={[0.027, 0.027, 0.026]}
              >
                <mesh
                  name="Object_114"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_114.geometry}
                  material={materials.SCREEN}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0025_107"
                position={[1.396, -0.232, 4.672]}
                rotation={[Math.PI / 2, 0, -0.309]}
                scale={0.026}
              >
                <mesh
                  name="Object_116"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_116.geometry}
                  material={materials["SCREEN.002"]}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0034_108"
                position={[0.793, 3.683, -5.776]}
                rotation={[Math.PI / 2, 0, 0.18]}
                scale={[0.026, 0.026, 0.025]}
              >
                <mesh
                  name="Object_118"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_118.geometry}
                  material={materials.SCREEN}
                />
              </group>
              <group
                name="OldTV_02_Low_OldTV_0035_109"
                position={[0.798, 3.683, -5.777]}
                rotation={[Math.PI / 2, 0, 0.18]}
                scale={0.025}
              >
                <mesh
                  name="Object_120"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_120.geometry}
                  material={materials["SCREEN.002"]}
                />
              </group>
              <group
                name="OldTV_03_Low_OldTV_0_111"
                position={[4.073, 0.181, -4.186]}
                rotation={[Math.PI / 2, 0, 0.592]}
                scale={[0.021, 0.027, 0.027]}
              >
                <mesh
                  name="Object_122"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_122.geometry}
                  material={materials.OldTV}
                />
              </group>
              <group
                name="OldTV_03_Low_OldTV_0001_112"
                position={[6.14, 0.181, 0.969]}
                rotation={[Math.PI / 2, 0, -0.539]}
                scale={[0.021, 0.027, 0.027]}
              >
                <mesh
                  name="Object_124"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_124.geometry}
                  material={materials.OldTV}
                />
              </group>
              <group
                name="OldTV_03_Low_OldTV_0002_113"
                position={[1.645, 0.153, 4.609]}
                rotation={[Math.PI / 2, 0, -0.313]}
                scale={[0.021, 0.027, 0.027]}
              >
                <mesh
                  name="Object_126"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_126.geometry}
                  material={materials.OldTV}
                />
              </group>
              <group
                name="OldTV_03_Low_OldTV_0003_114"
                position={[1.328, 0.159, -9.456]}
                rotation={[Math.PI / 2, 0, 0.396]}
                scale={[0.021, 0.027, 0.027]}
              >
                <mesh
                  name="Object_128"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_128.geometry}
                  material={materials.OldTV}
                />
              </group>
              <group
                name="OldTV_03_Low_OldTV_0004_115"
                position={[0.915, 3.902, -5.781]}
                rotation={[Math.PI / 2, 0, 0.167]}
                scale={[0.021, 0.027, 0.027]}
              >
                <mesh
                  name="Object_130"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_130.geometry}
                  material={materials.OldTV}
                />
              </group>
              <group
                name="OldTV_03_Low_OldTV_0005_116"
                position={[4.892, 3.902, -1.115]}
                rotation={[Math.PI / 2, 0, -0.212]}
                scale={[0.021, 0.027, 0.027]}
              >
                <mesh
                  name="Object_132"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_132.geometry}
                  material={materials.OldTV}
                />
              </group>
              <group
                name="OldTV_03_Low_OldTV_0006_117"
                position={[0.906, 3.902, 2.736]}
                rotation={[Math.PI / 2, 0, -0.649]}
                scale={[0.021, 0.027, 0.027]}
              >
                <mesh
                  name="Object_134"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_134.geometry}
                  material={materials.OldTV}
                />
              </group>
              <group
                name="OldTV_03_Low_OldTV_0007_118"
                position={[-2.229, 0.181, -4.412]}
                rotation={[Math.PI / 2, 0, 1.398]}
                scale={[0.021, 0.027, 0.027]}
              >
                <mesh
                  name="Object_136"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_136.geometry}
                  material={materials.OldTV}
                />
              </group>
              <group
                name="small-polka-dot-seamless-pattern-background-retro-vintage-vecto_119"
                position={[-7.754, 3.822, -2.763]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={20.74}
              >
                <mesh
                  name="Object_138"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_138.geometry}
                  material={
                    materials[
                      "small-polka-dot-seamless-pattern-background-retro-vintage-vecto"
                    ]
                  }
                />
              </group>
              <group
                name="Circle_120"
                position={[1.248, 0.169, -0.862]}
                scale={1.875}
              >
                <mesh
                  name="Object_140"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_140.geometry}
                  material={materials["SCREEN.001"]}
                />
              </group>
              <group
                name="Plane001_121"
                position={[5.899, 6.745, -2.436]}
                rotation={[-0.005, 0.38, -1.557]}
                scale={0.06}
              >
                <mesh
                  name="Object_142"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_142.geometry}
                  material={materials["Material.002"]}
                />
              </group>
              <group
                name="Plane002_122"
                position={[6.721, 3.038, -0.659]}
                rotation={[-0.03, 0.781, -1.528]}
                scale={0.081}
              >
                <mesh
                  name="Object_144"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_144.geometry}
                  material={materials["Material.002"]}
                />
              </group>
              <group
                name="Plane003_123"
                position={[2.976, 3.025, -9.896]}
                rotation={[-0.01, -0.234, -1.574]}
                scale={0.089}
              >
                <mesh
                  name="Object_146"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_146.geometry}
                  material={materials["Material.002"]}
                />
              </group>
              <group
                name="Plane004_124"
                position={[0.243, 9.627, -6.719]}
                rotation={[-0.009, -0.212, -1.496]}
                scale={0.055}
              >
                <mesh
                  name="Object_148"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_148.geometry}
                  material={materials["Material.002"]}
                />
              </group>
              <group
                name="Plane005_125"
                position={[1.697, 12.959, -2.593]}
                rotation={[-0.099, -0.108, -1.51]}
                scale={0.055}
              >
                <mesh
                  name="Object_150"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_150.geometry}
                  material={materials["Material.002"]}
                />
              </group>
              <group
                name="Plane006_126"
                position={[0.416, 9.838, 0.142]}
                rotation={[-0.124, -0.23, -1.53]}
                scale={0.055}
              >
                <mesh
                  name="Object_152"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_152.geometry}
                  material={materials["Material.002"]}
                />
              </group>
              <group
                name="Plane007_127"
                position={[-2.656, 4.825, -1.93]}
                scale={[3.373, 2.05, 2.05]}
              >
                <mesh
                  name="Object_154"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_154.geometry}
                  material={materials["SCREEN.001"]}
                />
              </group>
              <group
                name="Plane008_128"
                position={[-2.609, 0.653, 2.671]}
                rotation={[0.006, 0.699, -0.033]}
                scale={0.579}
              >
                <mesh
                  name="Object_156"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_156.geometry}
                  material={materials["SCREEN.001"]}
                />
              </group>
              <group
                name="Armature_180"
                position={[-2.109, 4.837, -1.469]}
                rotation={[Math.PI / 2, 0, 0.541]}
                scale={0.002}
              >
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_161"
                    geometry={nodes.Object_161.geometry}
                    material={materials.Material__20}
                    skeleton={nodes.Object_161.skeleton}
                  />
                  <skinnedMesh
                    name="Object_163"
                    geometry={nodes.Object_163.geometry}
                    material={materials["Material.001"]}
                    skeleton={nodes.Object_163.skeleton}
                  />
                  <group name="Object_2_178" />
                  <group name="Object_2001_179" />
                </group>
              </group>
              <group
                name="Empty_182"
                position={[3.572, 9.159, -2.796]}
                rotation={[0, 0.65, 0]}
                scale={[0.968, 0.938, 0.968]}
              >
                <group
                  name="OldTV_02_Low_OldTV_0026_181"
                  position={[-1.018, -2.025, -0.846]}
                  rotation={[Math.PI / 2, 0, 0.588]}
                  scale={0.024}
                >
                  <mesh
                    name="Object_215"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_215.geometry}
                    material={materials["SCREEN.003"]}
                  />
                </group>
              </group>
              <group name="Empty001_184" position={[5.081, 2.032, -3.325]}>
                <group
                  name="OldTV_02_Low_OldTV_0007_183"
                  position={[-1.018, -2.025, -0.846]}
                  rotation={[Math.PI / 2, 0, 0.588]}
                  scale={0.024}
                >
                  <mesh
                    name="Object_218"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_218.geometry}
                    material={materials["SCREEN.003"]}
                  />
                </group>
              </group>
              <group
                name="Empty002_186"
                position={[2.033, 5.775, 2.121]}
                rotation={[0, 1.247, 0]}
                scale={[1.105, 1.072, 1.105]}
              >
                <group
                  name="OldTV_02_Low_OldTV_0023_185"
                  position={[-1.018, -2.025, -0.846]}
                  rotation={[Math.PI / 2, 0, 0.588]}
                  scale={0.024}
                >
                  <mesh
                    name="Object_221"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_221.geometry}
                    material={materials["SCREEN.003"]}
                  />
                </group>
              </group>
              <group
                name="Empty003_188"
                position={[2.831, 1.939, 4.374]}
                rotation={[0, 0.898, 0]}
                scale={[1.105, 1.072, 1.105]}
              >
                <group
                  name="OldTV_02_Low_OldTV_0033_187"
                  position={[-1.018, -2.025, -0.846]}
                  rotation={[Math.PI / 2, 0, 0.588]}
                  scale={0.024}
                >
                  <mesh
                    name="Object_224"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_224.geometry}
                    material={materials["SCREEN.003"]}
                  />
                </group>
              </group>
              <group
                name="Empty004_190"
                position={[2.157, 5.781, -5.379]}
                rotation={[0, 0.408, 0]}
                scale={[1.069, 1.036, 1.069]}
              >
                <group
                  name="OldTV_02_Low_OldTV_0036_189"
                  position={[-1.018, -2.025, -0.846]}
                  rotation={[Math.PI / 2, 0, 0.588]}
                  scale={0.024}
                >
                  <mesh
                    name="Object_227"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_227.geometry}
                    material={materials["SCREEN.003"]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

